// Curated list of interesting words to look up via the dictionary API.
// These are chosen because they have clear, concise definitions that
// work well in a multiple-choice format.
const WORD_LIST = [
  "aberration", "abscond", "acumen", "admonish", "aesthetic",
  "affable", "alacrity", "ambivalent", "ameliorate", "anachronism",
  "anathema", "antithesis", "apocryphal", "arcane", "arduous",
  "ascetic", "assiduous", "atavism", "audacious", "auspicious",
  "avarice", "axiom", "baleful", "banal", "bellicose",
  "beneficent", "blandish", "blithe", "bombastic", "boorish",
  "bucolic", "byzantine", "cabal", "cacophony", "cadence",
  "cajole", "calumny", "candor", "capitulate", "capricious",
  "castigate", "catalyst", "caustic", "censure", "chagrin",
  "charlatan", "chimera", "circumspect", "clandestine", "clemency",
  "coalesce", "cogent", "commensurate", "compendium", "complacent",
  "conciliatory", "conflagration", "connoisseur", "consternation", "contrite",
  "conundrum", "convivial", "copious", "corroborate", "credulous",
  "culminate", "culpable", "cursory", "cynosure", "dearth",
  "debacle", "decorum", "deference", "defunct", "deleterious",
  "delineate", "denizen", "depravity", "deprecate", "derelict",
  "desiccate", "desultory", "diaphanous", "dichotomy", "didactic",
  "diffident", "digress", "dilatory", "diminutive", "dirge",
  "disaffected", "discerning", "disparage", "dissemble", "dissolution",
  "dissonance", "dither", "dogmatic", "doleful", "draconian",
  "ebullient", "eclectic", "edification", "effervescent", "effrontery",
  "egalitarian", "egregious", "elegy", "elucidate", "emaciate",
  "embellish", "emollient", "empirical", "enervate", "enigma",
  "ennui", "ephemeral", "equanimity", "equivocate", "erudite",
  "eschew", "esoteric", "ethereal", "eulogy", "euphemism",
  "evanescent", "exacerbate", "excoriate", "exemplary", "exigent",
  "exonerate", "expatiate", "expedient", "expunge", "extol",
  "extricate", "facetious", "fastidious", "fatuous", "feckless",
  "felicitous", "fervent", "filigree", "flagrant", "florid",
  "forlorn", "fortuitous", "fractious", "frenetic", "frugal",
  "furtive", "gainsay", "garrulous", "gauche", "grandiloquent",
  "gratuitous", "gregarious", "hackneyed", "halcyon", "hapless",
  "harbinger", "hedonist", "heretical", "hubris", "iconoclast",
  "idyllic", "ignominious", "immutable", "impassive", "impecunious",
  "imperious", "impervious", "implacable", "impudent", "inchoate",
  "incipient", "incongruous", "incorrigible", "indelible", "indigent",
  "indolent", "ineffable", "inexorable", "ingratiate", "inscrutable",
  "insidious", "insipid", "intractable", "intransigent", "intrepid",
  "invective", "inveterate", "irascible", "itinerant", "judicious",
  "juxtapose", "laconic", "languid", "lassitude", "laudable",
  "lethargic", "litigious", "lucid", "lugubrious", "luminous",
  "magnanimous", "malfeasance", "malinger", "malleable", "mendacious",
  "mercurial", "meticulous", "mitigate", "mollify", "morose",
  "munificent", "myopic", "nebulous", "nefarious", "neophyte",
  "nonchalant", "nonplussed", "noxious", "nuance", "obdurate",
  "obfuscate", "obsequious", "obstinate", "occlude", "officious",
  "onerous", "opaque", "opulent", "oscillate", "ostentatious",
  "pablum", "palatable", "panacea", "paradigm", "paragon",
  "parsimonious", "partisan", "patent", "patrician", "paucity",
  "pecuniary", "pedantic", "pellucid", "penchant", "penurious",
  "peremptory", "perfidious", "perfunctory", "peripatetic", "pernicious",
  "perspicacious", "pertinacious", "petulant", "philistine", "phlegmatic",
  "pithy", "platitude", "plethora", "polemical", "ponderous",
  "pragmatic", "precipitous", "preclude", "precocious", "predilection",
  "preponderance", "prescient", "presumptuous", "prevaricate", "probity",
  "proclivity", "prodigal", "prodigious", "profligate", "prolific",
  "propensity", "propitious", "prosaic", "protean", "provenance",
  "prudent", "pugnacious", "punctilious", "pusillanimous", "quagmire",
  "querulous", "quixotic", "quotidian", "raconteur", "rancorous",
  "rapacious", "recalcitrant", "recondite", "redoubtable", "refractory",
  "relegate", "remonstrate", "reparation", "replete", "reprobate",
  "repudiate", "rescind", "reticent", "reverent", "ribald",
  "rife", "ruminate", "sacrosanct", "sagacious", "salient",
  "salutary", "sanguine", "sardonic", "saturnine", "scintillate",
  "scrupulous", "sedulous", "shibboleth", "sinecure", "solicitous",
  "somnolent", "sophistry", "specious", "spurious", "squalid",
  "staid", "stentorian", "stolid", "strident", "stymie",
  "sublimate", "subterfuge", "succinct", "supercilious", "surfeit",
  "surreptitious", "sycophant", "taciturn", "temerity", "tempestuous",
  "tenacious", "tepid", "timorous", "torpid", "tractable",
  "transient", "trenchant", "truculent", "tumultuous", "turgid",
  "ubiquitous", "umbrage", "unctuous", "undulate", "unequivocal",
  "untenable", "urbane", "usurp", "utilitarian", "vacillate",
  "vacuous", "vapid", "variegated", "vehement", "venal",
  "venerable", "veracious", "verbose", "vestigial", "vicissitude",
  "vindictive", "virulent", "visceral", "vitriolic", "vituperate",
  "vociferous", "volatile", "voracious", "warranted", "winsome",
  "zealous",
];

// Static fallback entries used when the API is unavailable
const FALLBACK_BANK = [
  { word: "bailiwick", definition: "One's area of expertise or authority", wrong: ["A type of medieval weapon", "A small coastal inlet"] },
  { word: "petrichor", definition: "The pleasant smell of earth after rain", wrong: ["A type of fossilized amber", "A shade of dark green"] },
  { word: "defenestration", definition: "The act of throwing someone out of a window", wrong: ["Removing a fence or barrier", "A formal process of excommunication"] },
  { word: "saudade", definition: "A deep emotional longing for something absent", wrong: ["A traditional Portuguese dance", "A type of dry red wine"] },
  { word: "tsundoku", definition: "Acquiring books and letting them pile up unread", wrong: ["The art of Japanese gift wrapping", "A form of silent meditation"] },
  { word: "apricity", definition: "The warmth of the sun in winter", wrong: ["The ability to learn quickly", "A formal apology or retraction"] },
  { word: "fernweh", definition: "An ache for distant places; the opposite of homesickness", wrong: ["A type of German pastry", "Fear of dense forests"] },
  { word: "phosphene", definition: "The light you see when you rub your closed eyes", wrong: ["A chemical used in photography", "A type of deep-sea fish"] },
  { word: "clinomania", definition: "An excessive desire to stay in bed", wrong: ["A fear of steep hills", "An obsession with collecting clocks"] },
  { word: "vellichor", definition: "The strange wistfulness of used bookshops", wrong: ["A shade of deep purple", "An ancient stringed instrument"] },
];
